# Generated by Django 4.2.7 on 2023-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_image", models.ImageField(upload_to="originals", verbose_name="Исходное изображение")),
                (
                    "processed_image",
                    models.ImageField(blank=True, upload_to="processed", verbose_name="Обработанное изображение"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Queued"), (1, "Processing"), (2, "Done")], default=0, verbose_name="Статус"
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-added"],
            },
        ),
    ]
